openapi: 3.0.2
info:
  version: 1.0.0
  title: iStandaarden koppeling
  description: "Een standaard om gegevensuitwisseling tussen WIZportaal en de iStandaarden."

paths:
  /api/ijw/301/creeer:
    post:
      summary: Geeft een JW301 xml bericht als base64 terug
      tags:
        - iJw
      parameters:
        - in: body
          name: creeer301Bericht
          required: true
          schema:
            $ref: '#/components/schemas/creeerJW301Bericht'
      responses:
        '200':
          description: Een collectie aanvragen met beschikkingen en producten
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/creeer301Wrapper'
        '400':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/400"
        '401':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/401"
        '403':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/403"
        '406':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/406"
        '409':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/409"
        '410':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/410"
        '415':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/415"
        '429':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/429"
        '500':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/500"
        '501':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/501"
        '503':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/503"
        'default':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/default"
  /api/iwmo/301/creeer:
    post:
      summary: Geeft een WMO301 xml bericht als base64 terug
      tags:
        - iWmo
      parameters:
        - in: body
          name: creeer301Bericht
          required: true
          schema:
            $ref: '#/components/schemas/creeerWMO301Bericht'
      responses:
        '200':
          description: Een collectie aanvragen met beschikkingen en producten
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/creeer301Wrapper'
        '400':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/400"
        '401':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/401"
        '403':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/403"
        '406':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/406"
        '409':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/409"
        '410':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/410"
        '415':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/415"
        '429':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/429"
        '500':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/500"
        '501':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/501"
        '503':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/503"
        'default':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/default"
  /api/codelijsten/:
    get:
      summary: "Geeft de beschikbare collectie van de codelijst terug"
      tags:
        - codelijsten
      responses:
        '200':
          description: alle beschikbare codelijsten
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    $ref: '#/components/schemas/code'
        '400':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/400"
        '401':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/401"
        '403':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/403"
        '406':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/406"
        '409':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/409"
        '410':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/410"
        '415':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/415"
        '429':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/429"
        '500':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/500"
        '501':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/501"
        '503':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/503"
        'default':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/default"
  /api/codelijsten/{code}:
    get:
      summary: "Geeft de beschikbare codelijst terug"
      tags:
        - codelijsten
      parameters:
        - in: path
          name: code
          required: true
          schema:
            type: string
      responses:
        '200':
          description: de gevraagde codelijst
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/code'
        '400':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/400"
        '401':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/401"
        '403':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/403"
        '406':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/406"
        '409':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/409"
        '410':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/410"
        '415':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/415"
        '429':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/429"
        '500':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/500"
        '501':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/501"
        '503':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/503"
        'default':
          $ref: "https://raw.githubusercontent.com/open-sociaal-domein/generieke-componenten/master/common.yaml#/components/responses/default"

components:
  schemas:
    creeerJW301Bericht:
      type: object
      description: "Een JW301 json bericht dat getransformeert moet worden naar xml"
      properties:
        header:
          $ref: '#/components/schemas/wmoJwHeader'
        client:
          $ref: '#/components/schemas/wmoJwClient'
        relaties:
          type: array
          items:
            $ref: '#/components/schemas/wmoJwRelatie'
        beschikking:
          $ref: '#/components/schemas/wmoJwBeschikking'
        toegewezenProducten:
          type: array
          items:
            $ref: '#/components/schemas/wmoJwToegewezenProduct'

    creeerWMO301Bericht:
      type: object
      description: "Een WMO301 json bericht dat getransformeert moet worden naar xml"
      properties:
        header:
          $ref: '#/components/schemas/wmoJwHeader'
        client:
          $ref: '#/components/schemas/wmoJwClient'
        relaties:
          type: array
          items:
            $ref: '#/components/schemas/wmoJwRelatie'
        beschikking:
          $ref: '#/components/schemas/wmoJwBeschikking'
        toegewezenProducten:
          type: array
          items:
            $ref: '#/components/schemas/wmoJwToegewezenProduct'

    wmoJwToegewezenProduct:
      type: object
      description: Toegewezen product
      properties:
        toewijzingNummer:
          type: string
        referentieAanbieder:
          type: string
        product:
          $ref: '#/components/schemas/wmoJwProduct'
        toewijzingsdatum:
          type: string
        toewijzingstijd:
          type: string
        ingangsdatum:
          type: string
        einddatum:
          type: string
        redenWijziging:
          type: string
        omvang:
          $ref: '#/components/schemas/wmoJwOmvang'
        commentaar:
          type: string

    wmoJwProduct:
      type: object
      properties:
        categorie:
          type: string
        code:
          type: string

    wmoJwOmvang:
      type: object
      properties:
        volume:
          type: string
        eenheid:
          type: string
        frequentie:
          type: string

    wmoJwClient:
      type: object
      description: clientrecord volgens de Istandaarden
      properties:
        bsn:
          type: string
        geboortedatum:
          $ref: '#/components/schemas/wmoJwGeboortedatum'
        geslacht:
          $ref: '#/components/schemas/wmoJwGeslacht'
        naam:
          $ref: '#/components/schemas/wmoJwVolledigeNaam'
        contactAdressen:
          type: array
          items:
            $ref: '#/components/schemas/wmoJwContactAdres'
        juridischeStatus:
          type: string
          description: Codelijst WJ232
        commentaar:
          type: string

    wmoJwVolledigeNaam:
      type: object
      properties:
        geslachtsnaam:
          $ref: '#/components/schemas/wmoJwGeslachtsnaam'
        partnernaam:
          $ref: '#/components/schemas/wmoJwGeslachtsnaam'
        voornamen:
          type: string
          description: De verzameling namen die, gescheiden door spaties, aan de geslachtsnaam voorafgaat.
          maxLength: 200
        voorletters:
          type: string
          description: CS004, aaneengesloten zonder punten of spaties
          maxLength: 6
        naamGebruik:
          type: string
          description: Codelijst COD700
          enum:
            - '1'
            - '2'
            - '3'
            - '4'
            - '5'
            - '6'

      required:
        - geslachtsnaam
        - naamGebruik

    wmoJwGeboortedatum:
      type: object
      properties:
        datum:
          type: string
          format: date
        datumGebruik:
          type: string
          description: Indicator die aangeeft welk deel van de voorafgaande datum gebruikt mag worden. Zie codelijst COD170
          enum:
            - '1'
            - '2'
            - '3'

    wmoJwRelatie:
      type: object
      properties:
        nummer:
          type: string
          description: Identificerend nummer van de relatie van een client.
        volgorde:
          type: integer
          minimum: 0
          maximum: 99
        soort:
          type: string
          description: Enum, zie voor mogelijke relatiesoorten codelijst COD472
          maxLength: 2
        geboortedatum:
          $ref: '#/components/schemas/wmoJwGeboortedatum'
        geslacht:
          $ref: '#/components/schemas/wmoJwGeslacht'
        naam:
          type: string
        contactAdres:
          $ref: '#/components/schemas/wmoJwContactAdres'
      required:
        - nummer
        - soort
        - naam

    wmoJwGeslacht:
      type: string
      description: Codelijst COD046
      enum:
        - '0'
        - '1'
        - '2'
    wmoJwContactAdres:
      type: object
      properties:
        soort:
          type: string
          description: Codelijst COD757
          enum:
            - '01'
            - '02'
            - '03'
            - '04'
        adres:
          $ref: '#/components/schemas/wmoJwAdresDetails'
        organisatie:
          type: string
          maxLength: 35
        telefoon:
          type: object
          properties:
            telefoon01:
              $ref: '#/components/schemas/wmoJwTelefoon'
            telefoon02:
              $ref: '#/components/schemas/wmoJwTelefoon'
        emailadres:
          type: string
          format: email
        periode:
          type: object
          properties:
            begindatum:
              type: string
              format: date
            einddatum:
              type: string
              format: date

    wmoJwAdresDetails:
      type: object
      properties:
        huis:
          type: object
          properties:
            huisnummer:
              type: integer
              minimum: 0
              maximum: 99999
            huisletter:
              type: string
              maxLength: 1
            huisnummerToevoeging:
              type: string
              maxLength: 4
            aanduidingWoonadres:
              type: string
              enum:
                - AB
                - BY
                - TO
                - WW
          required:
            - huisnummer
        postcode:
          type: string
          description: CD034, Verplicht bij BRP-adres (1) of verblijfadres (3). CS089, bij landCode NL een valide postcode.
          maxLength: 8
        straatnaam:
          type: string
          maxLength: 24
        plaatsnaam:
          type: string
          maxLength: 80
        landCode:
          type: string
          maxLength: 2
          description: Enum, zie codelijst COD032. Verplicht als postcode gevuld is.

    wmoJwTelefoon:
      type: object
      properties:
        telefoonnummer:
          type: number
          description: CS005
          maxLength: 15
        landnummer:
          type: string
          maxLength: 4

    wmoJwGeslachtsnaam:
      type: object
      properties:
        achternaam:
          type: string
        voorvoegsel:
          type: string

    wmoJwBeschikking:
      type: object
      description: berichtheader voor zowel iWmo als iJw.
      properties:
        beschikkingNummer:
          type: string
        grondslagen:
          type: object
          properties:
            grondslag1:
              type: string
            grondslag2:
              type: string
        afgiftedatum:
          type: string
        ingangsdatum:
          type: string
        einddatum:
          type: string
        commentaar:
          type: string

    wmoJwHeader:
      type: object
      description: berichtheader voor zowel iWmo als iJw
      properties:
        afzender:
          type: string
          description: CBS gemeentecode van de gemeente die betrokken is bij de uitvoering van zorg of ondersteuning.
        dagtekening:
          type: string
          format: date
        identificatie:
          type: string
          description: Naam of nummer, die ter identificatie aan een totale aanlevering kan worden meegegeven.
          maxLength: 12
        ontvanger:
          type: string
          description: Valide AGB code

    creeer301Wrapper:
      type: object
      description: "Een JW of WMO 301 bericht als base64 met transformeer resultaat"
      properties:
        validationResult:
          $ref: '#/components/schemas/validationResult'
        xmlAsBase64String:
          type: string

    validationResult:
      type: object
      description: "resultaat van het van de gehele actie"
      properties:
        isValid:
          type: boolean
        schemaValidationResult:
          $ref: '#/components/schemas/schemaValidationResult'
        transformationValidationResult:
          $ref: '#/components/schemas/transformationValidationResult'

    schemaValidationResult:
      type: object
      description: "resultaat van de schema validatie"
      properties:
        isValid:
          type: boolean
        details:
          type: string

    transformationValidationResult:
      type: object
      description: "resultaat van de transformatie validatie"
      properties:
        isValid:
          type: boolean
        details:
          type: string

    code:
      type: object
      properties:
        code:
          type: string
        omschrijving:
          type: string
        ingangsDatum:
          type: string
          format: date
        expiratieDatum:
          type: string
          format: date
